# Generated by Django 5.0.1 on 2026-05-12 06:56

from django.db import migrations, models


def add_visual_embedding_column(apps, schema_editor):
    """Add visual_embedding column only if it doesn't exist"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DO $$ BEGIN
                ALTER TABLE products ADD COLUMN visual_embedding jsonb;
            EXCEPTION
                WHEN duplicate_column THEN NULL;
            END $$;
        """)


def add_role_column(apps, schema_editor):
    """Add role column only if it doesn't exist"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DO $$ BEGIN
                ALTER TABLE user_profiles ADD COLUMN role varchar(50) DEFAULT 'user';
            EXCEPTION
                WHEN duplicate_column THEN NULL;
            END $$;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_userprofile_rating_count'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    ALTER TABLE products ADD COLUMN visual_embedding jsonb;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END $$;
            """,
            reverse_sql="ALTER TABLE products DROP COLUMN IF EXISTS visual_embedding;",
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='visual_embedding',
                    field=models.JSONField(blank=True, help_text='2048-dim vector for visual search', null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    ALTER TABLE user_profiles ADD COLUMN role varchar(50) DEFAULT 'user';
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END $$;
            """,
            reverse_sql="ALTER TABLE user_profiles DROP COLUMN IF EXISTS role;",
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='role',
                    field=models.CharField(default='user', max_length=50),
                ),
            ],
        ),
    ]
