# Generated by Django 5.0.1 on 2026-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_product_visual_embedding_userprofile_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_primary'], name='product_ima_is_prim_873e82_idx'),
        ),
    ]
